app = 'cli.cpp'
test = 't.cpp'
libs = Glob('*.cpp', exclude=[app, test])
env = Environment(CXXFLAGS='-std=c++17 -Wall -Wextra -O2',
                  CPPDEFINES='RELEASE')
uxf_lib = env.Library('uxf', libs)
uxf_exe = env.Program('uxf', app, LIBS=['uxf'], LIBPATH='.')
test_exe = env.Program('t', test, LIBS=['uxf'], LIBPATH='.')
env.Install('../dist', uxf_lib)
env.Install('../dist', uxf_exe)
env.Install('../dist', test_exe)
