edition = "2021"
max_width = 76
# comment_width = 76
use_small_heuristics = "Max"
use_field_init_shorthand = true
# wrap_comments = true
# fn_args_density = "Compressed"
# format_strings = true
# merge_imports = true
# reorder_impl_items = true
